import { build as esbuild } from "esbuild"
import { dirname, join } from "node:path"
import { createFirebaseJson, createFirebaserc } from "../generate/firebase-json.js"
import { createFirestoreRules, createStorageRules } from "../generate/firebase-rules.js"
import { createFunctionsEntry } from "../generate/functions-entry.js"
import { createFunctionsPackage } from "../generate/functions-package.js"
import { loadConfig } from "./config-loader.js"
import { discoverFunctions, type DiscoveredFunction } from "./discover.js"
import { FirescopeError } from "./errors.js"
import { ensureDir, emptyDir, pathExists, writeFileIfMissing, writeFileSafe, writeJson } from "./fs.js"
import { color, log } from "./log.js"
import type { CliContext } from "./types.js"

export interface BuildResult {
  functions: DiscoveredFunction[]
  functionsRoot: string
  durationMs: number
}

function esbuildTarget(runtime: string): string {
  const major = runtime.replace(/[^0-9]/g, "")
  return major ? `node${major}` : "node22"
}

export async function buildCommand(context: CliContext): Promise<BuildResult> {
  const startedAt = Date.now()
  const config = await loadConfig(context.cwd)
  const source = config.functions.source ?? "src/functions"
  const sourceRoot = join(context.cwd, source)

  if (!(await pathExists(sourceRoot))) {
    throw new FirescopeError(
      `Functions source not found: ${source}`,
      `Create the ${source} directory, or change functions.source in firescope.config.ts.`,
    )
  }

  const functions = await discoverFunctions(context.cwd, source, config.functions.ignore ?? [])

  if (functions.length === 0) {
    log.warn(`No functions found in ${source}. Add a file, or underscore-prefix helpers to skip them.`)
  }

  const generatedRoot = join(context.cwd, ".firescope")
  const functionsRoot = join(generatedRoot, "functions")
  const entryPath = join(functionsRoot, "src", "index.ts")
  const outFile = join(functionsRoot, "lib", "index.js")

  await emptyDir(functionsRoot)
  await ensureDir(dirname(entryPath))
  await ensureDir(dirname(outFile))

  await writeFileSafe(entryPath, createFunctionsEntry(functions, entryPath, { functions: config.functions }))
  await writeJson(join(functionsRoot, "package.json"), await createFunctionsPackage(context.cwd))
  await writeFileSafe(
    join(functionsRoot, "README.md"),
    "# Generated by Firescope\n\nDo not edit this directory directly. Run `firescope build` instead.\n",
  )

  await esbuild({
    entryPoints: [entryPath],
    outfile: outFile,
    bundle: true,
    platform: "node",
    format: "esm",
    target: esbuildTarget(config.runtime),
    sourcemap: true,
    external: ["firebase-admin", "firebase-functions"],
    define: {
      "process.env.FIRESCOPE_REGION": JSON.stringify(config.region),
    },
    banner: {
      js: "import { createRequire as __firescopeCreateRequire } from 'node:module'; const require = __firescopeCreateRequire(import.meta.url);",
    },
  })

  await writeJson(join(context.cwd, "firebase.json"), createFirebaseJson(config))

  if (config.firestore !== false) {
    await writeFileIfMissing(join(context.cwd, config.firestore.rules ?? "firestore.rules"), createFirestoreRules())
  }

  if (config.storage !== false) {
    await writeFileIfMissing(join(context.cwd, config.storage.rules ?? "storage.rules"), createStorageRules())
  }

  if (config.project) {
    await writeJson(join(context.cwd, ".firebaserc"), createFirebaserc(config.project))
  }

  const label = `${functions.length} function${functions.length === 1 ? "" : "s"}`
  log.success(`Built ${label} into ${color.cyan(".firescope/functions")}`)

  if (functions.length > 0) {
    log.detail(functions.map((fn) => fn.name).join(", "))
  }

  return { functions, functionsRoot, durationMs: Date.now() - startedAt }
}
