import { build as esbuild } from "esbuild"
import { dirname, join } from "node:path"
import { resolveConfig } from "../config.js"
import { createFirebaseJson, createFirebaserc } from "../generate/firebase-json.js"
import { createFunctionsEntry } from "../generate/functions-entry.js"
import { createFunctionsPackage } from "../generate/functions-package.js"
import { loadConfig } from "./config-loader.js"
import { discoverFunctions } from "./discover.js"
import { ensureDir, emptyDir, pathExists, writeFileSafe, writeJson } from "./fs.js"
import { log } from "./log.js"
import type { CliContext } from "./types.js"

export async function buildCommand(context: CliContext): Promise<void> {
  const config = resolveConfig(await loadConfig(context.cwd))
  const source = config.functions.source ?? "src/functions"
  const sourceRoot = join(context.cwd, source)

  if (!(await pathExists(sourceRoot))) {
    throw new Error(`Functions source does not exist: ${source}`)
  }

  const functions = await discoverFunctions(context.cwd, source)
  const generatedRoot = join(context.cwd, ".firescope")
  const functionsRoot = join(generatedRoot, "functions")
  const entryPath = join(functionsRoot, "src", "index.ts")
  const outFile = join(functionsRoot, "lib", "index.js")

  await emptyDir(functionsRoot)
  await ensureDir(dirname(entryPath))
  await ensureDir(dirname(outFile))

  await writeFileSafe(entryPath, createFunctionsEntry(functions, entryPath))
  await writeJson(join(functionsRoot, "package.json"), await createFunctionsPackage(context.cwd, functionsRoot))
  await writeFileSafe(
    join(functionsRoot, "README.md"),
    "# Generated by Firescope\n\nDo not edit this directory directly. Run `firescope build` instead.\n",
  )

  await esbuild({
    entryPoints: [entryPath],
    outfile: outFile,
    bundle: true,
    platform: "node",
    format: "esm",
    target: config.runtime === "nodejs22" ? "node22" : "node20",
    sourcemap: true,
    external: ["firebase-admin", "firebase-functions", "firescope", "firescope/functions"],
    define: {
      "process.env.FIRESCOPE_REGION": JSON.stringify(config.region),
    },
    banner: {
      js: "import { createRequire as __firescopeCreateRequire } from 'node:module'; const require = __firescopeCreateRequire(import.meta.url);",
    },
  })

  await writeJson(join(context.cwd, "firebase.json"), createFirebaseJson(config))

  if (config.project) {
    await writeJson(join(context.cwd, ".firebaserc"), createFirebaserc(config.project))
  }

  log.success(`Built ${functions.length} function${functions.length === 1 ? "" : "s"} into .firescope/functions`)
}
